require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Rakefile
  ExcludedMethods:
    - route

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/ClassStructure:
  Enabled: true
