plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - '**/*.yml'
    - '**/*.yaml'
    - '**/.tool-versions'

Metrics/BlockLength:
  Exclude:
    - Rakefile
  AllowedMethods:
    - route

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/ClassStructure:
  Enabled: true

Style/Documentation:
  Enabled: false
  AllowedConstants:
    - App

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/html2rss/web/app/*_spec.rb'
    - 'spec/html2rss/web/app/health_check/auth_spec.rb'
