require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Rakefile

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/ClassStructure:
  Enabled: true

Style/Documentation:
  AllowedConstants:
    - App

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/html2rss/web/app/*_spec.rb'
    - 'spec/html2rss/web/app/health_check/auth_spec.rb'
