services:
  html2rss-web:
    image: html2rss/web:1
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      RACK_ENV: development
      HTML2RSS_ACCESS_TOKEN: CHANGE_ME_ADMIN_TOKEN
      BOTASAURUS_SCRAPER_URL: http://botasaurus:4010

  botasaurus:
    image: html2rss/botasaurus-scrape-api:latest
