# Docker Compose configuration for html2rss-web
# This is the default configuration - customize as needed

services:
  html2rss-web:
    image: gilcreator/html2rss-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - type: bind
        source: ./config/feeds.yml
        target: /app/config/feeds.yml
        read_only: true
    environment:
      RACK_ENV: production
      HTML2RSS_SECRET_KEY: your-generated-secret-key-here
      HEALTH_CHECK_USERNAME: health
      HEALTH_CHECK_PASSWORD: please-set-YOUR-OWN-veeeeeery-l0ng-aNd-h4rd-to-gue55-Passw0rd!
      BROWSERLESS_IO_WEBSOCKET_URL: ws://browserless:3001
      BROWSERLESS_IO_API_TOKEN: 6R0W53R135510

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/.docker/config.json:/config.json"
    command: --cleanup --interval 7200

  browserless:
    image: "ghcr.io/browserless/chromium"
    restart: unless-stopped
    environment:
      PORT: 3001
      CONCURRENT: 10
      TOKEN: 6R0W53R135510
