/** Sole UI copy owner for create / token / result journey states. */
export const COPY = {
  creating: 'Creating feed',
  previewChecking: 'Checking preview',
  feedReady: 'Feed ready',
  urlLabel: 'URL',
  urlPlaceholder: 'example.com/articles',
  feedUrl: 'Feed URL',
  tokenTitle: 'Access token',
  tokenHint: 'Instance access token (HTML2RSS_ACCESS_TOKEN).',
  tokenPlaceholder: 'Paste HTML2RSS_ACCESS_TOKEN',
  tokenRejected: 'Access token was rejected. Paste a valid token to continue.',
  /** Non-retryable / correct_input create failures (blocked, empty extract, …). */
  createFailedTitle: "Couldn't create feed",
  /** Retryable create failures where Try again remains honest. */
  createFailedRetryTitle: "Couldn't create feed yet",
  tryAgain: 'Try again',
  checkAgain: 'Check again',
  previewItemCount: (count: number) => `${count} items`,
  copy: 'Copy',
  copied: 'Copied!',
  creationDisabled: 'Feed creation is disabled on this instance.',
  /** Browse product name — SSOT with docs /feed-directory/ title. */
  feedDirectory: 'Feed Directory',
  /** Escape / utility CTA — verb + SSOT name; optional public catalog count. */
  browseFeedDirectory: (count = 0) =>
    count > 0 ? `Browse Feed Directory (${count})` : 'Browse Feed Directory',
  feedDirectoryIntro: 'Start with a ready-made feed from this instance.',
  feedDirectoryLearnMore: 'Learn how the Feed Directory works.',
  catalogFindHint: 'Matching feeds.',
  catalogFindHitsLabel: 'Matching feeds',
  dockerSetup: 'Set up your own instance with Docker.',
  dockerInstall: 'Install from Docker Hub',
  bookmarkletTitle: 'Bookmarklet',
  bookmarkletHelp:
    'Drag the Bookmarklet link from the footer to your bookmarks bar. On any page, click it to prefill the URL here.',
  bookmarkletDragHint: 'Drag this bookmarklet to your bookmarks bar',
  copyFeedUrl: 'Copy feed URL',
  openFeed: 'Open feed',
  openJsonFeed: 'Open JSON Feed',
  openInFeedReader: 'Open in feed reader',
  createAnother: 'Create another feed',
  createFeed: 'Create feed',
  saveAndContinue: 'Save and continue',
  back: 'Back',
  utilities: 'Utilities',
  logout: 'Logout',
  openapiSpec: 'OpenAPI spec',
  sourceCode: 'Source code',
  urlRequired: 'URL is required.',
  invalidUrlFormat: 'Invalid URL format.',
  unableToSaveToken: 'Unable to save access token.',
  unableToLoadToken: 'Unable to load access token.',
  unableToStartCreation: 'Unable to start feed creation.',
  instanceMetadataUnavailable: 'Instance metadata unavailable',
  accessTokenUnavailable: 'Access token unavailable',
  instanceUnavailable: 'Instance unavailable.',
  loadingInstance: 'Loading instance',
  loadingInstanceBody: 'Reading instance settings.',
  dismiss: 'Dismiss',
  authRequired: 'Access token is required.',
  checkUrlAndRetry: 'Check the URL.',
  unableToReachServer: 'Unable to reach the server.',
  unableToCompleteCreation: 'Unable to complete feed creation.',
  serverStillProcessing: 'The server is still processing the request.',
  previewUnavailable: 'Preview unavailable right now.',
  footerNav: 'Footer navigation',
  previewStatus: 'Feed preview status',
  previewRegion: 'Feed preview',
  itemsSelector: 'Items selector',
  enhanceItems: 'Enhance items',
  /** Ranked selector choices; buckets may be empty. */
  selectorChoices: 'Headline choices',
  selectorSuggestionsLoading: 'Finding selector choices',
  selectorSuggestionsEmpty: 'No additional selector choices found.',
  /** Suggest failure when wire message equals the unresolved Decision notice — never re-echo EXTRACTION_EMPTY. */
  selectorSuggestionsFailed: 'Selector choices unavailable',
  retrySelectorSuggestions: 'Try choices again',
  choicesFor: (name: string) => `${name} options`,
  addSelector: (label: string) => `Add ${label}`,
  removeSelector: (label: string) => `Remove ${label}`,
  saveAndGenerate: 'Save and generate feed',
  /** One-click YAML utility — no expandable preview. */
  copyYaml: 'Copy YAML',
  /** Ready-phase handoff — opens a prefilled Feed Directory GitHub issue. */
  proposeDirectory: 'Open Feed Directory issue',
  /** Compact one-click activators for dormant optional selector fields. */
  addOptionalFields: 'Add optional selectors',
  addOptionalField: (name: string) => `Add ${name}`,
  previewFetchedCaption: 'Based on the page already fetched for this URL',
  nativeFeedTitle: 'This site already publishes a feed.',
  fieldTitle: 'Title',
  fieldLink: 'Link',
  fieldPublished: 'Published date',
  fieldFound: (name: string) => `${name} — found`,
  fieldMissing: (name: string) => `${name} — not found`,
  selector: 'Selector',
} as const;
