/** Sole UI copy owner for create / token / result journey states. */
export const COPY = {
  creating: 'Creating feed',
  previewChecking: 'Checking preview',
  feedReady: 'Feed ready',
  urlLabel: 'URL',
  urlPlaceholder: 'example.com/articles',
  feedUrl: 'Feed URL',
  tokenTitle: 'Access token',
  tokenHint: 'Required by this instance.',
  tokenPlaceholder: 'Paste access token',
  tokenRejected: 'Access token was rejected. Paste a valid token to continue.',
  createFailedTitle: "Couldn't create feed yet",
  tryAgain: 'Try again',
  checkAgain: 'Check again',
  openOriginal: 'Open original',
  copy: 'Copy',
  copied: 'Copied!',
  creationDisabled: 'Feed creation is disabled on this instance.',
  includedFeedsTitle: 'Included feeds',
  includedFeedsIntro: 'Start with a ready-made feed from this instance.',
  includedFeedsLearnMore: 'Learn how included feeds work.',
  dockerSetup: 'Set up your own instance with Docker.',
  dockerInstall: 'Install from Docker Hub',
  bookmarkletTitle: 'Bookmarklet',
  bookmarkletHelp:
    'Drag the Bookmarklet link from the footer to your bookmarks bar. On any page, click it to prefill the URL here.',
  bookmarkletDragHint: 'Drag this bookmarklet to your bookmarks bar',
  copyFeedUrl: 'Copy feed URL',
  openFeed: 'Open feed',
  openJsonFeed: 'Open JSON Feed',
  openInFeedReader: 'Open in feed reader',
  createAnother: 'Create another feed',
  previewLatest: 'Latest items',
  createFeed: 'Create feed',
  saveAndContinue: 'Save and continue',
  back: 'Back',
  utilities: 'Utilities',
  tryIncludedFeeds: 'Try included feeds',
  logout: 'Logout',
  openapiSpec: 'OpenAPI spec',
  sourceCode: 'Source code',
  urlRequired: 'URL is required.',
  invalidUrlFormat: 'Invalid URL format.',
  unableToSaveToken: 'Unable to save access token.',
  unableToLoadToken: 'Unable to load access token.',
  unableToStartCreation: 'Unable to start feed creation.',
  instanceMetadataUnavailable: 'Instance metadata unavailable',
  instanceUnavailable: 'Instance unavailable.',
  loadingInstance: 'Loading instance',
  loadingInstanceBody: 'Reading instance settings.',
  dismiss: 'Dismiss',
  authRequired: 'Access token is required.',
  checkUrlAndRetry: 'Check the URL.',
  unableToReachServer: 'Unable to reach the server.',
  unableToCompleteCreation: 'Unable to complete feed creation.',
  serverStillProcessing: 'The server is still processing the request.',
  previewUnavailable: 'Preview unavailable right now.',
  previewBlockedSurface: 'This website blocked automated access.',
  previewScraperUnavailable: 'Feed fetching is temporarily unavailable.',
  footerNav: 'Footer navigation',
  previewStatus: 'Feed preview status',
  previewRegion: 'Feed preview',
} as const;
