/** Single-source UI copy for create / token / result journey states. */
export const COPY = {
  creating: 'Creating feed link',
  previewChecking: 'Checking preview',
  feedReady: 'Feed ready',
  pageUrl: 'Page URL',
  pageUrlPlaceholder: 'example.com/articles',
  feedUrl: 'Feed URL',
  tokenTitle: 'Access token',
  tokenHint: 'Required by this instance.',
  tokenPlaceholder: 'Paste access token',
  tokenRejected: 'Access token was rejected. Paste a valid token to continue.',
  createFailedTitle: "Couldn't create feed yet",
  tryAgain: 'Try again',
  checkAgain: 'Check again',
  openOriginal: 'Open original',
  copy: 'Copy',
  copied: 'Copied!',
  creationDisabled: 'Feed creation is disabled on this instance.',
  includedFeedsTitle: 'Included feeds',
  includedFeedsIntro: 'Start with a ready-made feed from this instance.',
  includedFeedsLearnMore: 'Learn how included configs work.',
  dockerSetup: 'Set up your own instance with Docker.',
  dockerInstall: 'Install from Docker Hub',
  bookmarkletTitle: 'Bookmarklet',
  bookmarkletHelp:
    'Drag the Bookmarklet link from the footer to your bookmarks bar. On any page, click it to prefill the URL here.',
  copyFeedUrl: 'Copy feed URL',
  openFeed: 'Open feed',
  openJsonFeed: 'Open JSON Feed',
  openInFeedReader: 'Open in feed reader',
  createAnother: 'Create another feed',
  previewLatest: 'Latest items',
  generateFeed: 'Generate feed URL',
  saveAndContinue: 'Save and continue',
  back: 'Back',
  utilities: 'Utilities',
  tryIncludedFeeds: 'Try included feeds',
  logout: 'Logout',
  openapiSpec: 'OpenAPI spec',
  sourceCode: 'Source code',
  sourceUrlRequired: 'Source URL is required.',
  invalidUrlFormat: 'Invalid URL format.',
  unableToSaveToken: 'Unable to save access token.',
  instanceMetadataUnavailable: 'Instance metadata unavailable',
  dismiss: 'Dismiss',
} as const;
