#!/usr/bin/env bash
set -e

# https://docs.travis-ci.com/user/best-practices-security/#recommendations-on-how-to-avoid-leaking-secrets-to-build-logs

git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git remote set-url origin "https://${GITHUB_TOKEN}@github.com/gildesmarais/html2rss-web.git" > /dev/null 2>&1
git checkout -b master
git pull

bundle update --source html2rss-configs
git add Gemfile.lock

git commit --message "chore: auto-update html2rss-configs [Travis Build # $TRAVIS_BUILD_NUMBER]"
git push --quiet --force-with-lease -u origin master
