#!/usr/bin/env bash
set -e

# https://docs.travis-ci.com/user/best-practices-security/#recommendations-on-how-to-avoid-leaking-secrets-to-build-logs

git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git clone "https://${GITHUB_TOKEN}@github.com/gildesmarais/html2rss-web.git" work > /dev/null 2>&1

cd work || exit 1
export BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/work/Gemfile"
bundle env
grep revision Gemfile.lock
# bundle update --gemfile 'work/Gemfile'
bundle
grep revision Gemfile.lock
bundle pristine html2rss-configs
grep revision Gemfile.lock
grep revision ../Gemfile.lock
git status
git diff
git add Gemfile.lock

git commit --message "chore: auto-update html2rss-configs [Travis Build # $TRAVIS_BUILD_NUMBER]"
git push --quiet -u origin master
cd ..
